---
version: "2"
services:
  musicexplorer:
      image: ghcr.io/mark-me/musicexplorer:v0.0.1
      container_name: musicexplorer
      volumes:
        - /media/ncp/music_explorer:/data
      restart: unless-stopped
