---
version: "2"
services:
  collection_loader:
    container_name: collection-loader
    volumes:
      - ${DIR_DATA}:/data
  musicexplorer:
    build:
      context: ./app
    image: ghcr.io/mark-me/musicexplorer:v0.0.1
    container_name: musicexplorer
    volumes:
      - ${DIR_DATA}:/data
    restart: unless-stopped

