---
version: "2"
services:
  collection_loader:
    container_name: collection-loader
    image: ghcr.io/mark-me/music_explorer_loader:v0.0.1
    volumes:
      - ${DIR_DATA}:/data
    restart: unless-stopped
  api:
    image: ghcr.io/mark-me/musicexplorer:v0.0.2
    container_name: api
    volumes:
      - ${DIR_DATA}:/data
    restart: unless-stopped
  browser:
    image: ghcr.io/mark-me/music_explorer_browser:v0.0.1
    container_name: browser
    depends_on:
      - api
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
  certbot-auto:
    container_name: certbot
    build:
      context: ./certbot-auto
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
  duckdns:
      image: ghcr.io/linuxserver/duckdns:version-369fbd5c
      container_name: duckdns
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Amsterdam
        - SUBDOMAINS=music-explorer
        - TOKEN=${DUCKDNS_TOKEN}
        - LOG_FILE=false #optional

