version: "3.8"

services:
  certbot-initial:
    build:
      context: ./certbot-initial
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    ports:
      - 80:80
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
